services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: npm run dev
    working_dir: /home/ubuntu/mise-docker
    volumes:
      - ./:/home/ubuntu/mise-docker
